### ISSUE TITLE
Installer created on non-windows doesn't install

### ISSUE THREAD

**Issue by jkudish** [electronjs/windows-installer#28]
I created an installer on a non-windows machine (Ubuntu 15.10 in this case) and tried to run the installer on a Windows machine. It loads up the default electron gif and then closes and nothing happens or installs.

Is there a debug file I can provide?

**Comment by paulcbetts** [comment]
Yep, can you provide `C:\Users\NAME\AppData\Local\SquirrelTemp\SqurrelSetup.log`?

**Comment by jkudish** [comment]
```2016-03-05 19:15:27> CheckForUpdateImpl: Reading RELEASES file from C:\Users\IEUser\AppData\Local\SquirrelTemp
2016-03-05 19:15:27> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-03-05 19:15:27> ApplyReleasesImpl: Writing files to app directory: C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\content_resources_200_percent.pak to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\content_resources_200_percent.pak
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\content_shell.pak to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\content_shell.pak
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\d3dcompiler_47.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\d3dcompiler_47.dll
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\ffmpeg.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\ffmpeg.dll
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\icudtl.dat to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\icudtl.dat
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\libEGL.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\libEGL.dll
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\libGLESv2.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\libGLESv2.dll
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\LICENSE to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\LICENSE
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\msvcp120.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\msvcp120.dll
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\msvcr120.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\msvcr120.dll
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\natives_blob.bin to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\natives_blob.bin
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\node.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\node.dll
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\pdf.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\pdf.dll
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\snapshot_blob.bin to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\snapshot_blob.bin
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\squirrel.exe to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\squirrel.exe
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\[app name censored].exe to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\[app name censored].exe
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\ui_resources_200_percent.pak to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\ui_resources_200_percent.pak
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\vccorlib120.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\vccorlib120.dll
2016-03-05 19:15:34> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\xinput1_3.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\xinput1_3.dll
2016-03-05 19:15:39> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\[app name censored].exe]
2016-03-05 19:15:39> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-03-05 19:15:39> ApplyReleasesImpl: Examining Pin: Command Prompt.lnk
2016-03-05 19:15:40> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2016-03-05 19:15:40> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2016-03-05 19:15:40> ApplyReleasesImpl: Fixing up tray icons
2016-03-05 19:15:40> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__f5(RegistryView view)
2016-03-05 19:15:40> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__f5(RegistryView view)
2016-03-05 19:15:40> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.0-beta7
2016-03-05 19:15:40> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.0-beta7
2016-03-05 19:15:50> Program: Starting Squirrel Updater: --install .
2016-03-05 19:15:50> Program: Starting install, writing to C:\Users\IEUser\AppData\Local\SquirrelTemp
2016-03-05 19:15:50> Program: About to install to: C:\Users\IEUser\AppData\Local\[app name censored]
2016-03-05 19:15:50> Program: Install path C:\Users\IEUser\AppData\Local\[app name censored] already exists, burning it to the ground
2016-03-05 19:15:50> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\IEUser\AppData\Local\[app name censored]\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
2016-03-05 19:15:50> CheckForUpdateImpl: Reading RELEASES file from C:\Users\IEUser\AppData\Local\SquirrelTemp
2016-03-05 19:15:50> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-03-05 19:15:50> ApplyReleasesImpl: Writing files to app directory: C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\content_resources_200_percent.pak to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\content_resources_200_percent.pak
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\content_shell.pak to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\content_shell.pak
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\d3dcompiler_47.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\d3dcompiler_47.dll
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\ffmpeg.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\ffmpeg.dll
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\icudtl.dat to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\icudtl.dat
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\libEGL.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\libEGL.dll
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\libGLESv2.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\libGLESv2.dll
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\LICENSE to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\LICENSE
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\msvcp120.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\msvcp120.dll
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\msvcr120.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\msvcr120.dll
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\natives_blob.bin to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\natives_blob.bin
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\node.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\node.dll
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\pdf.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\pdf.dll
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\snapshot_blob.bin to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\snapshot_blob.bin
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\squirrel.exe to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\squirrel.exe
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\[app name censored].exe to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\[app name censored].exe
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\ui_resources_200_percent.pak to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\ui_resources_200_percent.pak
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\vccorlib120.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\vccorlib120.dll
2016-03-05 19:15:54> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\lib\net45\xinput1_3.dll to C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\xinput1_3.dll
2016-03-05 19:16:00> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\IEUser\AppData\Local\[app name censored]\app-1.0.0-beta7\[app name censored].exe]
2016-03-05 19:16:03> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-03-05 19:16:03> ApplyReleasesImpl: Examining Pin: Command Prompt.lnk
2016-03-05 19:16:03> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2016-03-05 19:16:03> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2016-03-05 19:16:03> ApplyReleasesImpl: Fixing up tray icons
2016-03-05 19:16:03> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__f5(RegistryView view)
2016-03-05 19:16:03> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__f5(RegistryView view)
2016-03-05 19:16:03> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.0-beta7
2016-03-05 19:16:03> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.0-beta7```

Wondering if the `-beta7` is part of the problem?

**Comment by paulcbetts** [comment]
This log file looks like everything worked successfully, maybe your app itself isn't launching with `--squirrel-firstrun`?

**Comment by jkudish** [comment]
I am using https://github.com/mongodb-js/electron-squirrel-startup to set that stuff up.

```
require( 'electron-squirrel-startup' );
```

at the top of my main.js file.

**Comment by fellou89** [comment]
I'm running into the same issue as @jkudish, I've added `--squirrel-firstrun` to the electron-squirrel-startup as well to no avail, any suggestions?

I could add gist my SquirrelSetup.log but it's exactly the same as the one already on this thread

**Comment by voldmar** [comment]
@jkudish and @fellou89, I suppose that problem is in absence of resources and locales folders in your app folder. To (temporary) fix building process find `template.nuspec` in `node_modules/electron-winstaller` and replace backslashes to forward slashes. After that rebuild your windows installer, it should works after that.

**Comment by havenchyk** [comment]
@jkudish please, confirm, is solution from @voldmar working for you?

**Comment by wooandoo** [comment]
@havenchyk I confirm that the solution of @voldmar works for me on OSX; thanks
