### ISSUE TITLE
Failed to sign

### ISSUE THREAD

**Issue by john-griffin** [electronjs/windows-installer#32]
Not sure where to post this so starting here. When I try to sign our build using `certificateFile` and `certificatePassword` I get the following stack trace:

```
Failed with exit code: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to sign, command invoked was: 'C:\Users\John\Documents\GitHub\shrimp\node_modules\electron-winstaller\vendor\signtool.exe sign /a /f "C:\Users\John\Documents\GitHub\shrimp\cert.pfx" /p "fake-pass" C:\Users\John\AppData\Local\SquirrelTemp\tempb\lib\net45\shrimp.exe'
   at Squirrel.Update.Program.<signPEFile>d__9a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.Update.Program.<>c__DisplayClass78.<Releasify>b__6a(String pkgPath)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Failed to sign, command invoked was: 'C:\Users\John\Documents\GitHub\shrimp\node_modules\electron-winstaller\vendor\signtool.exe sign /a /f "C:\Users\John\Documents\GitHub\shrimp\cert.pfx" /p "fake-pass" C:\Users\John\AppData\Local\SquirrelTemp\tempb\lib\net45\shrimp.exe'
   at Squirrel.Update.Program.<signPEFile>d__9a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()<---

---> (Inner Exception #1) System.Exception: Failed to sign, command invoked was: 'C:\Users\John\Documents\GitHub\shrimp\node_modules\electron-winstaller\vendor\signtool.exe sign /a /f "C:\Users\John\Documents\GitHub\shrimp\cert.pfx" /p "fake-pass" C:\Users\John\AppData\Local\SquirrelTemp\tempb\lib\net45\squirrel.exe'
   at Squirrel.Update.Program.<signPEFile>d__9a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()<---
```

Couldn't see a clear problem in the trace, any ideas? Thanks!

**Comment by paulcbetts** [comment]
@john-griffin Try running the signtool command yourself and see what happens

**Comment by john-griffin** [comment]
Sorry for wasting your time. The issue was with our certificate provider Comodo. Using the signtool command directly did help isolate the problem. We have switched to DigiCert and all is working. Thanks!

**Comment by feross** [comment]
@john-griffin What was your issue with Comodo? I made the unfortunate mistake of using their cert too, and I'm regretting it. After you used signtool directly, what did you discover was the issue?

**Comment by john-griffin** [comment]
@feross never got to the bottom of it so asked for a refund. Went with DigiCert and it worked straight away!

**Comment by soichih** [comment]
I have a similar problem running on RHEL7 (which uses wine? to run the signtool.exe packaged for electron-winstaller/vendor)

When I ran the command used by winstaller on the terminal, I get following error message.

```
$ /home/hayashis/git/kdinstaller2/node_modules/electron-winstaller/vendor/signtool.exe sign /a /f "/home/hayashis/.ssh/sciapt_codesigning.pkcs12" /p "<<mypassword>>" /home/hayashis/.local/share/SquirrelTemp/tempa/lib/net45/kdinstall2.exe
err:module:import_dll Library MFC42.dll (which is needed by L"Z:\\home\\hayashis\\git\\kdinstaller2\\node_modules\\electron-winstaller\\vendor\\signtool.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"Z:\\home\\hayashis\\git\\kdinstaller2\\node_modules\\electron-winstaller\\vendor\\signtool.exe" failed, status c0000135
```

Do you know where I can obtain MFC42.dll and where I should install it?

**Comment by soichih** [comment]
Sorry. I found a solution for MFC42.dll issue.. All I have to do was `winetricks  mfc42`

However, now I am seeing a different error message..

```
/home/hayashis/git/kdinstaller2/node_modules/electron-winstaller/vendor/signtool.exe sign /a /f /home/hayashis/.ssh/sciapt_codesigning.pkcs12 /p "<<password>>" kdinstall2.exe
fixme:heap:HeapSetInformation (nil) 1 (nil) 0
SignTool Error: An error occurred while attempting to load the signing
	certificate from: /home/hayashis/.ssh/sciapt_codesigning.pkcs12
```

I can open my certificate fine using "openssl x509" with the same password configured for winstaller.

I am using a certificate from comodo, but the actual certificate is signed by InCommon. 

```
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=MI, L=Ann Arbor, O=Internet2, OU=InCommon, CN=InCommon RSA Code Signing CA
```

Could it be that signtool.exe that comes with winstaller is old / broken, etc?

**Comment by dougludlow** [comment]
Just ran into this error. I ran the signtool command manually and found that my code signing cert had expired.

**Comment by olifes-c** [comment]
@feross
